# Sesi 4 - Numpy

In [2]:
# install numpy buat yg belum ada anaconda
!pip install numpy

In [1]:
# import library
import numpy as np

In [3]:
# array
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
type(a)

numpy.ndarray

In [27]:
# Create blank list
my_list = []

In [ ]:
# beberapa function dari python
range()
print()
my_list.append()

In [26]:
# beberapa function dari numpy
# np.arange(1,5,2) # start dari 1, stop di 4 (5-1), step 2 --> sama kayak range()
# np.array()
np.empty(6)
np.append()
# np.zeros(5)
# np.ones(5)

array([0., 0., 0., 0., 0., 0.])

In [28]:
# create vector
b = np.array([1,2,3,4,5])
b

array([1, 2, 3, 4, 5])

In [29]:
# contoh append
np.append(b,[7,8,9])

array([1, 2, 3, 4, 5, 7, 8, 9])

In [30]:
# tidak berubah ketika kita panggil b nya lagi
b

array([1, 2, 3, 4, 5])

In [31]:
# jadi cara rubah b permanen, dgn cara overwrite :
b = np.append(b,[7,8,9])


In [34]:
b

array([1, 2, 3, 4, 5, 7, 8, 9])

In [35]:
# oops we miss 6
np.append(b,6, inplace=True)

TypeError: _append_dispatcher() got an unexpected keyword argument 'inplace'

error karena gabisa, gak ada prameter inplace, itu hanya di pandas

In [36]:
b = np.append(b,6)
b

array([1, 2, 3, 4, 5, 7, 8, 9, 6])

In [40]:
b = np.sort(b)
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
b.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [94]:
z = np.array([[1,2,3,4],[5,6,7,8],[10,11,12,13]])

In [95]:
z

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])

In [96]:
# change 5 and 7 to zero

z[ (z >= 5) & (z < 8) ]= 0                  # cara 1
# z = np.where(z >=5 & z <= 7, 0 , z)       # cara 2
# z[np.logical_and(z >= 5, z < 8)] = 0      # cara 3

In [97]:
z

array([[ 1,  2,  3,  4],
       [ 0,  0,  0,  8],
       [10, 11, 12, 13]])

In [98]:
# Perkalian vector ADA 2 METOD: `element wise` dan `dot product``

f = [1,2,3]
g = [4,5,6]
vect_f = np.array(f)
vect_g = np.array(g)
print('Hasil perkalian element wise')
print(vect_f * vect_g)
print('')

print('Hasil perkalian dot product')
print(vect_f.dot(vect_g)) # cara 1
print(vect_f@vect_g) # cara 2
print(np.dot(vect_f, vect_g)) # cara 3

Hasil perkalian element wise
[ 4 10 18]

Hasil perkalian dot product
32
32
32


# Studi Kasus

```
teks_1 = saya pergi ke rumah kakek saya
teks_2 = saya pergi ke rumah nenek saya
```

In [99]:
# Pendefinisian vector sebab string tidak bisa terbaca, jd harus diconversi ke numeric
# Langkah 1 cari unique words dlu, [saya,pergi,ke,rumah,kakek,nenek]
# Langkah 2 teks 1 muncul berapa kali saya,pergi,dst? [2,1,1,1,1,0]
# Langkah 3 teks 2 muncul berapa kali saya,pergi,dst? [2,1,1,1,0,1]
t1 = [2,1,1,1,1,0]
t2 = [2,1,1,1,0,1]

vect_t1 = np.array(t1)
vect_t2 = np.array(t2)

cos_theta = (vect_t1@vect_t2) / (np.linalg.norm(vect_t1) * np.linalg.norm(vect_t2))
cos_theta

0.8749999999999998

In [100]:
# perkalian vector (Matrix Multiplication) menggunakan @ jika shape matrix berbeda

A = [[1,2],
     [3,4],
     [5,6]]

B = [[1,2],
     [3,4]]     

matrix_A = np.array(A)
matrix_B = np.array(B)

print(matrix_A@matrix_B)

[[ 7 10]
 [15 22]
 [23 34]]
